name: Compila y genera PDF

on:
  push:

jobs:
  compila_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Hello World Action By Hugo Montes
        uses: HugoMontes/actions-javascript@v1.1
        with: 
          who-to-greet: Juan Perez
      - name: Descargar codigo del repositorio al runner
        uses: actions/checkout@v4.3.1
      - name: Instalar .NET en el runner
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.0.x'
      - name: Instalar dependencias
        run: dotnet restore
      - name: Compilar
        run: dotnet build --no-restore

  crear_pdf_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: true
      - uses: actions/upload-artifact@v5
        with:
          name: docs
          path: pdfs
